import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Slider from '../components/Slider.jsx';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>DoughMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider />
    </div>
  )
}
